=== Guyutongxue/guyutongxue.github.io/json/projects.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "title": "List of Projects",
    "items": {
        "type": "object",
        "properties": {
            "name": {
                "type": "string",
                "title": "Project Name"
            },
            "img": {
                "type": "string",
                "format": "uri",
                "title": "Showing Image"
            },
            "discription": {
                "type": "string",
                "title": "A brief discription to the project"
            },
            "link": {
                "type": "string",
                "format": "uri",
                "title": "Link to the homepage"
            },
            "update": {
                "type": "string",
                "format": "date",
                "title": "The recent update time"
            }
        },
        "required": [
            "name", "img"
        ]
    }
}

=== Guyutongxue/guyutongxue.github.io/json/projects.json
[
    {
        "name": "VS Code Config Helper",
        "img": "https://guyutongxue.github.io/VSCodeConfigHelper/assets/VSCodeConfigHelper.png",
        "discription": "简单、快捷的 VS Code C++ 配置工具",
        "link": "https://guyutongxue.github.io/VSCodeConfigHelper/",
        "update": "2020-06-02"
    },
    {
        "name": "Dev-C++ Theme",
        "img": "https://github.com/Guyutongxue/DevCppTheme/raw/master/icon.png",
        "discription": "仿 Dev-C++ 的 VS Code 主题",
        "link": "https://marketplace.visualstudio.com/items?itemName=Guyutongxue.devcpp-theme",
        "update": "2020-05-31"
    },
    {
        "name": "Amazons",
        "img": "https://s1.ax1x.com/2020/06/12/tXfFZ6.png",
        "discription": "《计算概论 A》大作业——亚马逊棋，Windows平台下的纯控制台程序",
        "link": "https://github.com/Guyutongxue/Amazons",
        "update": "2020-01-01"
    },
    {
        "name": "copyfile 2",
        "img": "https://s1.ax1x.com/2020/06/14/NSISzV.png",
        "discription": "自动复制插入计算机的存储设备的内容（中学时用来对付某些老师的课件）",
        "link": "https://github.com/Guyutongxue/copyfile2",
        "update": "2018-05-07"
    },
    {
        "name": "Statistics Tool",
        "img": "https://s1.ax1x.com/2020/06/14/NSINSP.png",
        "discription": "快速统计人名的工具。中学时经常用于统计回执、作业的收集情况",
        "link": "https://github.com/Guyutongxue/StatisticsTool",
        "update": "2018-03-23"
    },
    {
        "name": "摇号器",
        "img": "https://s1.ax1x.com/2020/06/14/NSonts.png",
        "discription": "简单的摇号器，支持一些高级选项如避开某号或确定某号",
        "link": "https://github.com/Guyutongxue/RandomTool",
        "update": "2018-03-09"
    }
]
